/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class UpdateProjectRequestBodyMetadata extends SpeakeasyBase {}

export class UpdateProjectRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "custom_identifier" })
    customIdentifier?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => UpdateProjectRequestBodyMetadata)
    metadata?: UpdateProjectRequestBodyMetadata;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "thumb" })
    thumb?: string;
}

export class UpdateProjectRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody: UpdateProjectRequestBody;

    /**
     * Project id
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
    id: number;
}

export class UpdateProject200ApplicationJSONMetadata extends SpeakeasyBase {}

/**
 * Successful operation
 */
export class UpdateProject200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "custom_identifier" })
    customIdentifier?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => UpdateProject200ApplicationJSONMetadata)
    metadata?: UpdateProject200ApplicationJSONMetadata;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "thumb" })
    thumb?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "wallet_connection" })
    walletConnection?: string;
}

export class UpdateProjectResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successful operation
     */
    @SpeakeasyMetadata()
    updateProject200ApplicationJSONObject?: UpdateProject200ApplicationJSON;
}
